'use server'
import { z } from 'zod'
import { txn } from '@/lib/db'
import { getRestaurant } from '@/server/queries'
import { getSessionUser } from '@/server/current-user'
import { listAccruals, type Accrual } from '@/server/accrual-queries'
import { postJournalEntryTx } from '@/server/journal'
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
const Schema = z.object({ name: z.string().trim().min(1).max(120), accrualDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), reversalDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable(), amount: z.string().regex(/^\d{1,11}(\.\d{1,2})?$/), expenseAccountId: z.string().regex(UUID), liabilityAccountId: z.string().regex(UUID) })
export type AccrualResult = { ok: true; accruals: Accrual[] } | { ok: false; error: string }
async function actor() { const user = await getSessionUser(); if (!user || !['accountant', 'owner'].includes(user.role)) throw new Error('Only an accountant or owner can manage accruals'); return user.username }
export async function createAccrual(raw: unknown): Promise<AccrualResult> { try { const input = Schema.parse(raw); const by = await actor(); if (input.expenseAccountId === input.liabilityAccountId) throw new Error('Choose different expense and liability accounts'); const restaurant = await getRestaurant(); const rid = restaurant.id; await txn(async (tx) => { const accounts = await tx<{ id: string; account_type: string }[]>`select id, account_type from accounting_accounts where restaurant_id = ${rid} and (id = ${input.expenseAccountId} or id = ${input.liabilityAccountId}) and status = 'active'`; if (accounts.length !== 2 || accounts.find((a) => a.id === input.expenseAccountId)?.account_type !== 'expense' || accounts.find((a) => a.id === input.liabilityAccountId)?.account_type !== 'liability') throw new Error('Choose an active expense account and an active liability account'); await tx`insert into accruals (restaurant_id, name, accrual_date, reversal_date, amount, expense_account_id, liability_account_id, created_by) values (${rid}, ${input.name}, ${input.accrualDate}, ${input.reversalDate}, ${input.amount}, ${input.expenseAccountId}, ${input.liabilityAccountId}, ${by})` }); return { ok: true, accruals: await listAccruals(rid) } } catch (error) { return { ok: false, error: error instanceof z.ZodError ? 'Enter valid accrual details' : error instanceof Error ? error.message : 'The accrual could not be saved' } } }
export async function postAccrual(id: string, kind: 'accrual' | 'reversal'): Promise<AccrualResult> { try { if (!UUID.test(id)) throw new Error('Malformed accrual id'); const by = await actor(); const restaurant = await getRestaurant(); const rid = restaurant.id; await txn(async (tx) => { const [a] = await tx<{ id: string; name: string; accrual_date: string; reversal_date: string | null; amount: string; expense_account_id: string; liability_account_id: string; status: string }[]>`select id, name, accrual_date::text, reversal_date::text, amount::text, expense_account_id, liability_account_id, status from accruals where restaurant_id = ${rid} and id = ${id} for update`; if (!a || a.status === 'retired') throw new Error('Accrual not found or retired'); if (kind === 'reversal' && a.reversal_date === null) throw new Error('Set a reversal date before reversing this accrual'); const [run] = await tx<{ id: string }[]>`insert into accrual_postings (restaurant_id, accrual_id, posting_kind) values (${rid}, ${id}, ${kind}) on conflict (restaurant_id, accrual_id, posting_kind) do nothing returning id`; if (!run) throw new Error(`The ${kind} has already been posted`); const date = kind === 'accrual' ? a.accrual_date : a.reversal_date!; const journalId = await postJournalEntryTx(tx, rid, { date, sourceType: `accrual_${kind}`, sourceId: run.id, memo: `${kind === 'accrual' ? 'Accrual' : 'Reversal'}: ${a.name}`, postedBy: by, lines: [{ accountId: a.expense_account_id, debit: kind === 'accrual' ? a.amount : '0', credit: kind === 'reversal' ? a.amount : '0', description: a.name }, { accountId: a.liability_account_id, debit: kind === 'reversal' ? a.amount : '0', credit: kind === 'accrual' ? a.amount : '0', description: a.name }] }); await tx`update accrual_postings set journal_entry_id = ${journalId} where restaurant_id = ${rid} and id = ${run.id}`; if (kind === 'reversal') await tx`update accruals set status = 'reversed' where restaurant_id = ${rid} and id = ${id}` }); return { ok: true, accruals: await listAccruals(rid) } } catch (error) { return { ok: false, error: error instanceof Error ? error.message : 'The accrual could not be posted' } } }
