'use server'
import { z } from 'zod'
import { txn } from '@/lib/db'
import { getRestaurant } from '@/server/queries'
import { getSessionUser } from '@/server/current-user'
import { listFixedAssets, type FixedAsset } from '@/server/fixed-asset-queries'
import { postJournalEntryTx } from '@/server/journal'
const UUID = /^[0-9a-f-]{36}$/i
const Schema = z.object({ code: z.string().trim().min(1).max(40), name: z.string().trim().min(1).max(120), purchaseDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), inServiceDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), cost: z.string().regex(/^\d{1,11}(\.\d{1,2})?$/), salvageValue: z.string().regex(/^\d{1,11}(\.\d{1,2})?$/), usefulLifeMonths: z.number().int().min(1).max(1200), assetAccountId: z.string().regex(UUID), depreciationExpenseAccountId: z.string().regex(UUID), accumulatedDepreciationAccountId: z.string().regex(UUID) })
export type FixedAssetResult = { ok: true; assets: FixedAsset[] } | { ok: false; error: string }
async function actor() { const user = await getSessionUser(); if (!user || !['accountant', 'owner'].includes(user.role)) throw new Error('Only an accountant or owner can manage fixed assets'); return user.username }
export async function createFixedAsset(raw: unknown): Promise<FixedAssetResult> { try { const input = Schema.parse(raw); const by = await actor(); if (input.inServiceDate < input.purchaseDate) throw new Error('In-service date cannot precede purchase date'); if (Number(input.salvageValue) >= Number(input.cost)) throw new Error('Salvage value must be below cost'); const restaurant = await getRestaurant(); const rid = restaurant.id; await txn(async (tx) => { const accounts = await tx<{ id: string; account_type: string }[]>`select id, account_type from accounting_accounts where restaurant_id = ${rid} and id in (${input.assetAccountId}, ${input.depreciationExpenseAccountId}, ${input.accumulatedDepreciationAccountId}) and status = 'active'`; if (accounts.length !== 3 || accounts.find((a) => a.id === input.assetAccountId)?.account_type !== 'asset' || accounts.find((a) => a.id === input.depreciationExpenseAccountId)?.account_type !== 'expense' || accounts.find((a) => a.id === input.accumulatedDepreciationAccountId)?.account_type !== 'asset') throw new Error('Choose active asset, depreciation-expense, and accumulated-depreciation accounts'); await tx`insert into fixed_assets (restaurant_id, asset_code, name, purchase_date, in_service_date, cost, salvage_value, useful_life_months, asset_account_id, depreciation_expense_account_id, accumulated_depreciation_account_id, created_by) values (${rid}, ${input.code.toUpperCase()}, ${input.name}, ${input.purchaseDate}, ${input.inServiceDate}, ${input.cost}, ${input.salvageValue}, ${input.usefulLifeMonths}, ${input.assetAccountId}, ${input.depreciationExpenseAccountId}, ${input.accumulatedDepreciationAccountId}, ${by})` }); return { ok: true, assets: await listFixedAssets(rid) } } catch (error) { return { ok: false, error: error instanceof z.ZodError ? 'Enter valid fixed-asset details' : error instanceof Error ? error.message : 'The fixed asset could not be saved' } } }
export async function postDepreciation(assetId: string, periodDate: string): Promise<FixedAssetResult> { try { if (!UUID.test(assetId) || !/^\d{4}-\d{2}-\d{2}$/.test(periodDate)) throw new Error('The depreciation details are invalid'); const by = await actor(); const restaurant = await getRestaurant(); const rid = restaurant.id; await txn(async (tx) => { const [asset] = await tx<{ id: string; name: string; in_service_date: string; cost: string; salvage_value: string; useful_life_months: number; depreciation_expense_account_id: string; accumulated_depreciation_account_id: string; status: string }[]>`select id, name, in_service_date::text, cost::text, salvage_value::text, useful_life_months, depreciation_expense_account_id, accumulated_depreciation_account_id, status from fixed_assets where restaurant_id = ${rid} and id = ${assetId} for update`; if (!asset || asset.status !== 'active') throw new Error('Fixed asset is not active'); if (periodDate < asset.in_service_date) throw new Error('Depreciation date precedes the in-service date'); const [run] = await tx<{ id: string; amount: string }[]>`insert into fixed_asset_depreciation (restaurant_id, asset_id, period_date, amount) select ${rid}, ${assetId}, ${periodDate}::date, least(round((f.cost - f.salvage_value) / f.useful_life_months, 2), f.cost - f.salvage_value - coalesce((select sum(d.amount) from fixed_asset_depreciation d where d.restaurant_id = f.restaurant_id and d.asset_id = f.id), 0)) from fixed_assets f where f.restaurant_id = ${rid} and f.id = ${assetId} on conflict (restaurant_id, asset_id, period_date) do nothing returning id, amount::text`; if (!run || Number(run.amount) <= 0) throw new Error('This period is already posted or the asset is fully depreciated'); const journalId = await postJournalEntryTx(tx, rid, { date: periodDate, sourceType: 'fixed_asset_depreciation', sourceId: run.id, memo: `Depreciation: ${asset.name}`, postedBy: by, lines: [{ accountId: asset.depreciation_expense_account_id, debit: run.amount, description: asset.name }, { accountId: asset.accumulated_depreciation_account_id, credit: run.amount, description: asset.name }] }); await tx`update fixed_asset_depreciation set journal_entry_id = ${journalId} where restaurant_id = ${rid} and id = ${run.id}` }); return { ok: true, assets: await listFixedAssets(rid) } } catch (error) { return { ok: false, error: error instanceof Error ? error.message : 'Depreciation could not be posted' } } }
