'use server'
import { z } from 'zod'
import { txn } from '@/lib/db'
import { getRestaurant } from '@/server/queries'
import { getSessionUser } from '@/server/current-user'
import { listRecurringTemplates, type RecurringTemplate } from '@/server/recurring-queries'
import { postJournalEntryTx } from '@/server/journal'
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
const Schema = z.object({ name: z.string().trim().min(1).max(120), dayOfMonth: z.number().int().min(1).max(28), startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), endDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable(), lines: z.array(z.object({ accountId: z.string().regex(UUID), description: z.string().trim().max(120), debit: z.string().regex(/^\d{1,11}(\.\d{1,2})?$/), credit: z.string().regex(/^\d{1,11}(\.\d{1,2})?$/) })).min(2).max(20) })
export type RecurringResult = { ok: true; templates: RecurringTemplate[] } | { ok: false; error: string }
async function actor() { const user = await getSessionUser(); if (!user || !['accountant', 'owner'].includes(user.role)) throw new Error('Only an accountant or owner can manage recurring entries'); return user.username }
export async function createRecurringTemplate(raw: unknown): Promise<RecurringResult> { try { const input = Schema.parse(raw); const by = await actor(); const restaurant = await getRestaurant(); const rid = restaurant.id; const debit = input.lines.reduce((n, line) => n + Number(line.debit), 0); const credit = input.lines.reduce((n, line) => n + Number(line.credit), 0); if (debit <= 0 || debit.toFixed(2) !== credit.toFixed(2)) throw new Error('Recurring lines must balance exactly'); await txn(async (tx) => { const [template] = await tx<{ id: string }[]>`insert into recurring_journal_templates (restaurant_id, name, day_of_month, start_date, end_date, created_by) values (${rid}, ${input.name}, ${input.dayOfMonth}, ${input.startDate}, ${input.endDate}, ${by}) returning id`; for (const line of input.lines) await tx`insert into recurring_journal_template_lines (restaurant_id, template_id, account_id, description, debit, credit) values (${rid}, ${template.id}, ${line.accountId}, ${line.description === '' ? null : line.description}, ${line.debit}, ${line.credit})` }); return { ok: true, templates: await listRecurringTemplates(rid) } } catch (error) { return { ok: false, error: error instanceof z.ZodError ? 'Enter a balanced recurring entry with valid dates and accounts' : error instanceof Error ? error.message : 'The template could not be saved' } } }
export async function runRecurringTemplate(templateId: string, periodDate: string): Promise<RecurringResult> { try { if (!UUID.test(templateId) || !/^\d{4}-\d{2}-\d{2}$/.test(periodDate)) throw new Error('The recurring run details are invalid'); const by = await actor(); const restaurant = await getRestaurant(); const rid = restaurant.id; await txn(async (tx) => { const [template] = await tx<{ id: string; name: string; day_of_month: number; start_date: string; end_date: string | null }[]>`select id, name, day_of_month, start_date::text as start_date, end_date::text as end_date from recurring_journal_templates where restaurant_id = ${rid} and id = ${templateId} and status = 'active' for update`; if (!template) throw new Error('Recurring template is not active'); if (periodDate.slice(8) !== String(template.day_of_month).padStart(2, '0')) throw new Error('The run date must use the template day of month'); if (periodDate < template.start_date || (template.end_date !== null && periodDate > template.end_date)) throw new Error('The run date is outside the template dates'); const [run] = await tx<{ id: string }[]>`insert into recurring_journal_runs (restaurant_id, template_id, period_date) values (${rid}, ${templateId}, ${periodDate}) on conflict (restaurant_id, template_id, period_date) do nothing returning id`; if (!run) throw new Error('This recurring period has already been posted'); const lines = await tx<{ account_id: string; description: string | null; debit: string; credit: string }[]>`select account_id, description, debit::text, credit::text from recurring_journal_template_lines where restaurant_id = ${rid} and template_id = ${templateId} order by id`; const journalId = await postJournalEntryTx(tx, rid, { date: periodDate, sourceType: 'recurring_journal', sourceId: run.id, memo: `Recurring: ${template.name}`, postedBy: by, lines: lines.map((line) => ({ accountId: line.account_id, description: line.description ?? undefined, debit: line.debit, credit: line.credit })) }); await tx`update recurring_journal_runs set journal_entry_id = ${journalId} where restaurant_id = ${rid} and id = ${run.id}` }); return { ok: true, templates: await listRecurringTemplates(rid) } } catch (error) { return { ok: false, error: error instanceof Error ? error.message : 'The recurring entry could not be posted' } } }
