'use client'

import { useState } from 'react'
import { saveStockTransfer } from '@/server/transfer-actions'
import type { TransferableItem } from '@/server/transfer-queries'
import { btnCls, cardCls, fieldLabelCls, inputCls, numCls, selectCls } from '@/components/ui'

export default function StockTransferForm({ today, locations, items }: { today: string; locations: { id: string; name: string }[]; items: TransferableItem[] }) {
  const [date, setDate] = useState(today); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [itemId, setItemId] = useState(''); const [qty, setQty] = useState(''); const [note, setNote] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null)
  const available = items.filter((item) => item.location_id === from); const selected = available.find((item) => item.id === itemId)
  async function submit() { setBusy(true); setMessage(null); try { const result = await saveStockTransfer({ date, fromLocationId: from, toLocationId: to, note, lines: [{ itemId, qty }] }); setMessage(result.ok ? 'Transfer recorded.' : result.error); if (result.ok) { setItemId(''); setQty(''); setNote('') } } catch { setMessage('Could not reach the server — nothing was transferred') } finally { setBusy(false) } }
  const valid = !busy && from !== '' && to !== '' && from !== to && selected !== undefined && Number(qty) > 0 && Number(qty) <= Number(selected.on_hand_qty)
  return <section className={cardCls}><h2 className="font-display text-lg font-bold text-stone-900">Move stock between locations</h2><p className="mt-1 text-sm text-stone-600">Transfer all or part of an item’s lot balance; total stock and value do not change.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label><span className={fieldLabelCls}>Date</span><input type="date" value={date} onChange={(e) => setDate(e.target.value)} className={`${numCls} w-full`} /></label><label><span className={fieldLabelCls}>Note</span><input value={note} onChange={(e) => setNote(e.target.value)} maxLength={300} className={inputCls} /></label><label><span className={fieldLabelCls}>From</span><select value={from} onChange={(e) => { setFrom(e.target.value); setItemId(''); setQty('') }} className={selectCls}><option value="">Choose source…</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><label><span className={fieldLabelCls}>To</span><select value={to} onChange={(e) => setTo(e.target.value)} className={selectCls}><option value="">Choose destination…</option>{locations.filter((location) => location.id !== from).map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><label><span className={fieldLabelCls}>Item</span><select value={itemId} onChange={(e) => { const value = e.target.value; setItemId(value); setQty(available.find((item) => item.id === value)?.on_hand_qty ?? '') }} className={selectCls}><option value="">Choose item…</option>{available.map((item) => <option key={`${item.id}-${item.location_id}`} value={item.id}>{item.code} · {item.name} ({item.on_hand_qty} {item.purchase_unit})</option>)}</select></label><label><span className={fieldLabelCls}>Quantity</span><input value={qty} onChange={(e) => setQty(e.target.value)} inputMode="decimal" className={numCls} /></label></div><button type="button" disabled={!valid} onClick={() => void submit()} className={`${btnCls} mt-4`}>{busy ? 'Saving…' : 'Record transfer'}</button>{message && <p className="mt-3 text-sm text-stone-700">{message}</p>}</section>
}
